language: java

dist: trusty
sudo: required

jdk:
    - openjdk11
    - oraclejdk8

# osx images only support one jdk per image, so manually add them to the matrix.
matrix:
    include:
        - os: osx
          osx_image: xcode9.3
          jdk: oraclejdk8
        - os: osx
          osx_image: xcode10.1
          jdk: openjdk11

addons:
    sonarcloud:
        organization: "powsybl-ci-github"
        token:
            secure: ${SONAR_TOKEN}

install:
# Build powsybl-core
- git clone https://github.com/powsybl/powsybl-core powsybl/powsybl-core
- pushd powsybl/powsybl-core && mvn --batch-mode -DskipTests install && popd

script:
- mvn --batch-mode -Pjacoco,checks clean verify sonar:sonar

